In [12]:
# Python program to interchange first and last elements in a list
n = int(input("Enter the number in the list : "));
l = [];
for i in range(0,n):
    j = int(input())
    l.append(j)
    
print("----------------------------------")
i=0;
l[i] = l[i] + l[n-1];
l[n-1] = l[i]-l[n-1];
l[i] = l[i] - l[n-1];

for i in range(0,n):
    print(l[i]);


Enter the number in the list : 5
3
2
4
1
5
----------------------------------
5
2
4
1
3


In [24]:
# swap any two element of the list
n = int(input("Enter the number of elements in the list: "))
l = []

print("Enter the elements:")
for i in range(n):
    j = int(input())
    l.append(j)

print("Enter the positions of the elements to swap :")
ind1 = int(input("Position 1: "))
ind2 = int(input("Position 2: "))

# Swap the elements at pos1 and pos2
l[ind1], l[ind2] = l[ind2], l[ind1]

print("List after swapping elements:")
for i in range(n):
    print(l[i])


Enter the number of elements in the list: 5
Enter the elements:
2
4
1
5
8
Enter the positions of the elements to swap (0-based index):
Position 1: 3
Position 2: 1
List after swapping elements:
2
5
1
4
8


In [14]:
# length of the list
n = int(input("Enter the number in the list : "));
l = [];
for i in range(0,n):
    j = int(input())
    l.append(j)
    
print("----------------------------------")
count =0;
for i in range(0,n):
    count = count+1
print("Length of the list is : ",count)

Enter the number in the list : 5
2
3
1
4
5
----------------------------------
Length of the list is :  5


In [2]:
count=0;
for i in l:
    count = count+1
print("Length of the kist is : ",count)

Length of the kist is :  5


In [22]:
# Maximum of two numbers in Python
n = int(input("Enter the number in the list : "));
l = [];
for i in range(0,n):
    j = int(input())
    l.append(j)
    
print("----------------------------------")

print("Enter the positions of the elements to swap (0-based index):")
ind1 = int(input("Position 1: "))
ind2 = int(input("Position 2: "))



if(l[ind1]==l[ind2]):
    print(f"{l[ind1]} id equal to {l[ind2]}");
elif(l[ind1]>l[ind2]):
    print(f"{l[ind1]} is greater than {l[ind2]}");
else:
    print(f"{l[ind2]} is greater than {l[ind1]}");

Enter the number in the list : 5
1
2
4
5
3
----------------------------------
Enter the positions of the elements to swap (0-based index):
Position 1: 2
Position 2: 4
4 is greater than 3


In [23]:
# Minimum of two numbers in Python
n = int(input("Enter the number in the list : "));
l = [];
for i in range(0,n):
    j = int(input())
    l.append(j)
    
print("----------------------------------")

print("Enter the positions of the elements to swap (0-based index):")
ind1 = int(input("Position 1: "))
ind2 = int(input("Position 2: "))



if(l[ind1]==l[ind2]):
    print(f"{l[ind1]} id equal to {l[ind2]}");
elif(l[ind1]<l[ind2]):
    print(f"{l[ind1]} is smaller than {l[ind2]}");
else:
    print(f"{l[ind2]} is smaller than {l[ind1]}");

Enter the number in the list : 4
5
2
3
1
----------------------------------
Enter the positions of the elements to swap (0-based index):
Position 1: 0
Position 2: 2
3 is smaller than 5


In [33]:
# Python program to check whether the string is Symmetrical or Palindrome
def is_symmetrical(s):
    length = len(s)
    mid = length // 2
    if length % 2 == 0:
        first_half = s[:mid]
        second_half = s[mid:]
    else:
        first_half = s[:mid]
        second_half = s[mid+1:]
    return first_half == second_half

def is_palindrome(s):
    return s == s[::-1]


s = input("Enter any string: ")


if is_symmetrical(s):
    print(f"{s} is symmetrical")
else:
    print(f"{s} is not symmetrical")

# Check if the string is a palindrome
if is_palindrome(s):
    print(f"{s} is a palindrome")
else:
    print(f"{s} is not a palindrome")


Enter any string: tikit
tikit is not symmetrical
tikit is a palindrome


In [ ]:
# Reverse words in a given String in Python
s = input("Enter any string: ")
l = list(s)
n=len(s)
i=0;
j=n-1;
while i<j:
    l[i], l[j] = l[j], l[i]
    i=i+1;
    j=j-1;

reversed_string = ''.join(l)  
print(reversed_string)

In [3]:
# Function to take user input for tuple matrix
def tuple_matrix():
    # Take the number of rows and columns as input
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))

    # Initialize an empty list to store the matrix rows
    matrix = []

    # Loop through each row
    for i in range(rows):
        # Initialize an empty list to store the current row elements
        row = []
        print(f"Enter elements for row {i+1}:")
        # Loop through each column to take input for the current row
        for j in range(cols):
            element = int(input(f"Element {j+1}: "))
            row.append(element)
        # Convert the current row list to a tuple and add it to the matrix
        matrix.append(tuple(row))

    # Convert the list of tuples to a tuple of tuples
    matrix = tuple(matrix)
    return matrix

# Call the function and get the tuple matrix
matrix = tuple_matrix()

# Print the resulting tuple matrix
print("The tuple matrix is:")
for row in matrix:
    print(row)

matrix=list(matrix)
row_sums=[]
for row in matrix:
    row_sum = sum(row)
    row_sums.append(row_sum)

sum_tuple=tuple(row_sums)
print(sum_tuple)

Enter the number of rows: 3
Enter the number of columns: 3
Enter elements for row 1:
Element 1: 1
Element 2: 2
Element 3: 3
Enter elements for row 2:
Element 1: 4
Element 2: 2
Element 3: 3
Enter elements for row 3:
Element 1: 5
Element 2: 6
Element 3: 4
The tuple matrix is:
(1, 2, 3)
(4, 2, 3)
(5, 6, 4)
(6, 9, 15)


In [4]:
l=[]
n=int(input("enter n: "))
for i in range(n):
    e=int(input(f"Enter {i+1} element: "))
    l.append(e)
tuple_list = [(num,num**3) for num in l]
print(tuple_list)

enter n: 5
Enter1 element: 2
Enter2 element: 3
Enter3 element: 4
Enter4 element: 1
Enter5 element: 5
[(2, 8), (3, 27), (4, 64), (1, 1), (5, 125)]


In [1]:
my_dict = {'apple': 3, 'banana': 1}
key = input();

# Attempt to access a key
try:
    check = my_dict[key]
except KeyError:
    check = 'Key not found'

print("Key Check:", check)


rohit
Key Check: Key not found


In [24]:
# Create a fresh script with just this content

# Define a dictionary
my_dict = {'apple': 3, 'banana': 1, 'cherry': 2}

# Sort the dictionary by keys
sorted_by_keys = dict(sorted(my_dict.items()))

# Print the sorted dictionary
print("Sorted by keys:", sorted_by_keys)



TypeError: 'dict' object is not callable

In [26]:
my_dict={}
n = int(input("Enter number of enteries: "))

for i in range(n):
    key = input("Enter Keys : ")
    values = int(input("Enter integer values : "))
    
    my_dict[key]=values

print("Dict->",my_dict)
total_sum = sum(my_dict.values())
print("Sum of items -> ",total_sum)

Enter number of enteries: 3
Enter Keys : item1
Enter integer values : 23
Enter Keys : item2
Enter integer values : 21
Enter Keys : item3
Enter integer values : 12
Dict-> {'item1': 23, 'item2': 21, 'item3': 12}
Sum of items ->  56


In [28]:
my_dict
count = 0
for i in my_dict:
    count +=1
print(count)

3


In [31]:
set_=[]
n=int(input())
for i in range(n):
    j=input()
    set_.append(j)
s=set(set_)
print(s)


5
6
3
2
5
9
{'2', '6', '5', '9', '3'}


In [37]:
s
count = 0
for i in s:
    count +=1
print(count)
max_value = None
for value in s:
    if max_value is None or value > max_value:
        max_value = value
print(max_value)

min_value = None
for val in s:
    if min_value is None or val < min_value:
        min_value = val
print(min_value)

5
9
2


In [40]:
l1=[1,2,3,4,5]
l2=[2,4,3,6,7]
for i in l1:
    if i in l2:
        
        print(f"{l1[i]} is common in both")
else:
    print("No element common")

3 is common in both
4 is common in both
5 is common in both
No element common


In [41]:
import numpy as np

# Define the first row
first_row = np.array([1, 2, 3, 4])

# Define the number of rows for the matrix
num_rows = 5

# Create a matrix with subsequent rows assigned to the first row's elements
# Initialize a matrix with zeros
matrix = np.zeros((num_rows, len(first_row)), dtype=int)

# Assign the first row to the matrix
matrix[0] = first_row

# Assign subsequent rows based on the first row's elements
# Example: setting subsequent rows as multiples of the first row's elements
for i in range(1, num_rows):
    matrix[i] = first_row * (i + 1)

# Print the resulting matrix
print("Matrix:")
print(matrix)


Matrix:
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]


In [42]:
import numpy as np

# Define two matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Add the matrices
matrix_sum = np.add(matrix_a, matrix_b)

# Subtract the matrices
matrix_diff = np.subtract(matrix_a, matrix_b)

# Print the results
print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nSum of Matrix A and Matrix B:")
print(matrix_sum)
print("\nDifference of Matrix A and Matrix B:")
print(matrix_diff)



Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Sum of Matrix A and Matrix B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Difference of Matrix A and Matrix B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [43]:
import numpy as np

def group_elements_to_matrix(elements):
    # Create a dictionary to hold the groups
    grouped_elements = {}

    # Group elements
    for element in elements:
        if element not in grouped_elements:
            grouped_elements[element] = []
        grouped_elements[element].append(element)

    # Find the size of the largest group to determine matrix dimensions
    max_group_size = max(len(group) for group in grouped_elements.values())

    # Create a matrix with the appropriate dimensions
    num_groups = len(grouped_elements)
    matrix = np.zeros((num_groups, max_group_size), dtype=int)

    # Fill the matrix with grouped elements
    for i, group in enumerate(grouped_elements.values()):
        for j, element in enumerate(group):
            matrix[i, j] = element

    return matrix

# Example elements list
elements = [1, 2, 2, 3, 1, 4, 3, 2, 1]

# Create the matrix
result_matrix = group_elements_to_matrix(elements)

# Print the resulting matrix
print("The grouped elements matrix is:")
print(result_matrix)


The grouped elements matrix is:
[[1 1 1]
 [2 2 2]
 [3 3 0]
 [4 0 0]]
